### ISSUE TITLE
Implement pagination

### ISSUE THREAD

**Issue by ma3yta** [corneliutusnea/aurelia-grid#1]
Please implement pagination

**Comment by corneliutusnea** [comment]
Done
https://github.com/corneliutusnea/aurelia-grid/commit/748d6a6d9a8a53ad7e8bf79fa7adae38ee0dd960
Pager now works. It also supports custom user templates but I need to update the documentation.

**Comment by corneliutusnea** [comment]
@Ma3yTa I've improved the pagination to support also custom templates:
https://github.com/corneliutusnea/aurelia-grid/blob/master/docs/pager.md
