### ISSUE TITLE
Binding to Parent viewmodel properties and function does not work - Solution

### ISSUE THREAD

**Issue by uwascan** [corneliutusnea/aurelia-grid#6]
Hi, 
Your current implementation deos not work when you try to bind a button in a grid-col to a function in the parent viewmodel like below:

```
          <grid-col can-sort="true" heading="Salary" field="salary" class="col-xs-3" can-filter="true">
            <button class="btn btn-info btn-xs" click.trigger="onItemClicked($item)">
              Transfer
            </button>
          </grid-col>
```

It errors out saying `onItemClicked` is not a function
Solution
1. in grid.ts, change the bind function definition from
`bind(bindingContext)` to `bind(bindingContext, overrideContext)`
2. Change the last line in bind function from `this.builder.build();`  to `this.builder.build(bindingContext, overrideContext);`
3. In grid-builder.ts, change the build function def from 

```
    build() {
        // Listen for window resize so we can re-flow the grid layout
        this.resizeListener = window.addEventListener('resize', this.headersSyncColumnHeadersWithColumns.bind(this));

        this.buildHeadingTemplate();
        this.buildRowTemplate();
        this.buildPagerTemplate();
    }
```

to

```
    build(bindingContext, overrideContext) {
        // Listen for window resize so we can re-flow the grid layout
        this.resizeListener = window.addEventListener('resize', this.headersSyncColumnHeadersWithColumns.bind(this));

        this.buildHeadingTemplate(bindingContext, overrideContext);
        this.buildRowTemplate(bindingContext, overrideContext);
        this.buildPagerTemplate(bindingContext, overrideContext);
    }
```
1. Still in grid-builder.ts, change the function definitions `buildHeadingTemplate()`, `buildRowTemplate()` and  `buildPagerTemplate()` to `buildHeadingTemplate(bindingContext, overrideContext)`, `buildRowTemplate(bindingContext, overrideContext)` and `buildPagerTemplate(bindingContext, overrideContext)` respectively. Then in each of the above functions, change the lines where you call `view.bind()` to 
   `view.bind(this.grid, overrideBindingContext);` where `overrideBindingContext` is declared as

```
    let overrideBindingContext = {
      bindingContext: this.grid,
      parentOverrideContext: {
        bindingContext: bindingContext,
        parentOverrideContext: overrideContext
      }
    };
```

The variable `overrideBindingContext` creates like a cascade of context objects that will allow any functions and properties in the parent viewmodels to be reached (without using $parent) from within grid-column templates.

A PR would be in order but I don't yet do Typescript all my test was done on the transpilled code. 
I hope this helps.

The motivation for this was the understanding I gained while reading your source code (beautiful code by the way. Your sense of organization is simply wonderful), which enabled me solve the same problem for [charlespockert aurelia-bs-grid](https://github.com/charlespockert/aurelia-bs-grid) which this code is also based on.

Thank you

**Comment by ManojRanga** [comment]
I am using java script. I am facing the same issue. How can I solve this issue in java script.
I tried using $parent once and twice, still that didn't work.
@uwascan please help me to resolve this issue.

**Comment by corneliutusnea** [comment]
@ManojRanga @uwascan Fixed in this last build however I could not make the binding automatically go from parent to parent so you need to use `$p` to reach the real parent of the grid.
Happy to do adjustments to make the parent binding work automatically if you can find a way.
