### ISSUE TITLE
this.dataRead is not a function

### ISSUE THREAD

**Issue by crystoll** [corneliutusnea/aurelia-grid#8]
It seems to me as if there's an error with delegated datasource implementation. Code in grid-delegated-source is referring to dataRead function that is not defined anywhere. Corresponding code in grid-local-source has these lines, that are missing from grid-delegate-source:

```
                this.dataRead = grid.sourceRead;
                if (!this.dataRead) {
                    throw new Error("'data-read.call' is not defined on the grid.");
                }
```

**Comment by ErikSchierboom** [comment]
I have found the same bug.

**Comment by corneliutusnea** [comment]
@crystoll @ErikSchierboom  You will get that error if you did not define the `source-read.call="myfunction()"` on the grid.
See the documentation https://github.com/corneliutusnea/aurelia-grid/blob/master/docs/datasource.md#delegated-data-source

**Comment by boettr** [comment]
Can confirm that even when I have source-read.call defined that I am getting this error.

Looks as though it is as a result of the NPM package being out of date as Master contains a working version that includes the following few lines of code in grid-delegate-source.js

`this.dataRead = grid.sourceRead;
                    if (!this.dataRead) {
                        throw new Error("'data-read.call' is not defined on the grid.");
                    }`

the NPM version does not.
